# This is a basic workflow to help you get started with Actions这是一个基本的工作流程，可以帮助你开始使用Actions

name: CI   名字:CI

# Controls when the workflow will run#控制工作流何时运行
on:   :
  # Triggers the workflow on push or pull request events but only for the "main" branch#在推或拉请求事件上触发工作流，但只针对“主”分支
  push:   推动:
    branches: [ "main" ]   分支:["main"   “主要”]
  pull_request:
    branches: [ "main" ]   分支:["main"   “主要”]

  # Allows you to run this workflow manually from the Actions tab#允许您从Actions选项卡手动运行此工作流
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel工作流运行由一个或多个作业组成，这些作业可以顺序运行，也可以并行运行
jobs:   工作:
  # This workflow contains a single job called "build"#这个工作流包含一个名为“build”的任务
  build:   构建:
    # The type of runner that the job will run on#作业将运行的运行器类型
    runs-on: ubuntu-latest   上运行:ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job# Steps表示将作为作业的一部分执行的一系列任务
    steps:   步骤:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it签出$GITHUB_WORKSPACE下的存储库，以便您的作业可以访问它
      - uses: actions/checkout@v4-使用:actions/checkout@v4

      # Runs a single command using the runners shell#使用运行器shell运行单个命令
      - name: Run a one-line script—name:执行一行脚本
        run: echo Hello, world!   运行:echo Hello, world!

      # Runs a set of commands using the runners shell#使用运行器shell运行一组命令
      - name: Run a multi-line script—name:执行多行脚本
        run: |   运行:|
          echo Add other actions to build,为构建添加其他操作，
          echo test, and deploy your project.回显测试，并部署项目。
