# Simple workflow for deploying static content to GitHub Pages#简单的工作流程部署静态内容到GitHub页面
name: Deploy static content to Pagesname:将静态内容部署到Pages

on: 
  workflow_dispatch:
schedule:
- cron:"0  2 * * 1-5"
  # Runs on pushes targeting the default branch#针对默认分支推送运行
  push:   推动:
    branches: ["main"]   分支机构(“主要”):

  # Allows you to run this workflow manually from the Actions tab#允许您从Actions选项卡手动运行此工作流
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages#设置GITHUB_TOKEN的权限，允许部署到GitHub页面
permissions:   权限:
  contents: read   内容:读
  pages: write   页:写
  id-token: write   id-token:写

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.#只允许一个并发部署，跳过正在运行和最新队列之间的运行队列。
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.但是，不要取消正在进行的运行，因为我们希望这些生产部署能够完成。
concurrency:   并发性:
  group: "pages"   组:“页面”
  cancel-in-progress: false   cancel-in-progress:假

  jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
  # Single deploy job since we're just deploying#单部署作业，因为我们只是在部署
  deploy:   部署:
    environment:   环境:
      name: github-pages   名称:github-pages
      url: ${{ steps.deployment.outputs.page_url }}Url: ${{steps.deployment.output .page_url}}
    runs-on: ubuntu-latest   上运行:ubuntu-latest
    steps:   步骤:
      - name: Checkout   -名称:Checkout
        uses: actions/checkout@v4   用途:行动/ checkout@v4
      - name: Setup Pages   —name:设置页面
        uses: actions/configure-pages@v5用途:行动/ configure-pages@v5
      - name: Upload artifact   —name:上传工件
        uses   使用: actions/upload-pages-artifact@v3用途:行动/ upload-pages-artifact@v3
        with   与:
          #上传整个存储库# Upload entire repository#上传整个存储库
          path   路径: '.'   “。”
      - name   名字: Deploy to GitHub Pages- name:部署到GitHub页面
        id: deployment   id:部署
        uses   使用: actions/deploy-pages@v4用途:行动/ deploy-pages@v4
